sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "node"
git:
  depth: 1
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

notifications:
  irc: "irc.freenode.org#socket.io"
